### ISSUE TITLE
Should imagenet stats for place dataset be used?

### ISSUE THREAD

**Issue by gloriamacia** [afzalsayed96/intel_scene_classification#1]
Hey! I was going through your amazing work. Thanks for sharing
In 2-intel_fastai_res50_places.ipynb you are loading places weights but using image_net stats. Not sure if this is correct. Just to make sure.

**Comment by afzalsayed96** [comment]
Hey,

You have to pass stats to normalize dataset and you have to calculate stats
based on the dataset. But imagenet_stats are decent enough and it is safe
to assume that it should work with most image datasets which it did in our
case.

You can read more about it here:
https://docs.fast.ai/vision.data.html#ImageDataBunch.normalize

If you are running the experiments yourself then feel free to try without
imagenet_stats and see how it varies.

**Comment by gloriamacia** [comment]
Ah, thanks a lot! I was really wondering. Awesome code, Afzal. Quick questions (just curiosity): you talk about different ensembles. How many models you end up using at the end?

**Comment by afzalsayed96** [comment]
Hey,

There were not many different models (most of them were resnet50 with
places365) but rather different techniques such as mixup, TTA, etc were
used in ensembling. If I remember correctly I ended up ensembling around 50
submissions with various combination of techniques used in each of them to
get the final solution.

You can read more about it in my write-up here:

“1st Place Solution for Intel Scene Classification Challenge” by Afzal
Sayed https://link.medium.com/E1XlHajGAY

**Comment by gloriamacia** [comment]
Awesome! Congrats again :) Feel free to add me on linkedin. Truly great work!
